### ISSUE TITLE
后续需要做的事情

### ISSUE THREAD

**Issue by fushang318** [sibbay-ai/token#11]
智能合约后续需要做如下事情

1. 修改剩余的问题，详情 https://github.com/sibbay-ai/token/issues/12   需要 @hnuyx 完成
2. 整理 token 版本库，把 python 代码移出去，只留下合约代码 需要 @fushang318 完成
3. 整理测试点矩阵 需要 @hnuyx 完成， @fushang318 详细 review   https://github.com/sibbay-ai/token/issues/14
4. 基于测试点矩阵，设计所有测试用例的描述 需要 @hnuyx 完成， @fushang318 详细 review  https://github.com/sibbay-ai/token/issues/14
5. 基于测试用例的描述，编写基于 web3 python lib 的测试代码 需要 @hnuyx 完成， @fushang318 详细 review
6. 部署测试链，运行测试代码 需要 @fushang318 在一台机器上挂这运行（需要时间比较长）

**Comment by hnuyx** [comment]
1. 可以移除，也可以保留。没有安全问题。
2. 测试阶段的费用，还是按原来讲好的的3.5 size吧
3. 好的，可以ICP

**Comment by fushang318** [comment]
好的，我来安排

**Comment by hnuyx** [comment]
@fushang318 这个可以关闭了
