### ISSUE TITLE
协商安比审计事宜

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#29]
1. 审计的流程
2. 审计的内容
3. 审计需要配合提供的资源
4. 审计的价格

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-09-04 size:0.5 @fushang318

**Comment by fushang318** [comment]
具体审计的话，需要我们提供什么内容
文档，代码或者流程图，还是专人介绍业务，签合同？
除了报价可能更关心的是，他们是否足够专业以及我们如何配合完成目标

**Comment by hnuyx** [comment]
补充:
审计需要提供资料：token源码，token设计文档（可能需要）
审计时间，暂定3周

交付物：
1. 审计规范中的审计报告
2. 测试用例的代码覆盖度详细信息，包括覆盖的代码和可能未覆盖的代码

审计阶段大致有两个阶段：
1. 审计公司根据token源码，全面分析，提供所有的修改意见。并交由我们修改
2. 修改完成的代码再次审计，并输出最终的审计报告和可部署的合约代码。

期间可能需要多次修改，并交付审计。

**Comment by fushang318** [comment]
我最关心的几个问题

1. 目前最复杂的业务接口是，锁定期转账，这个需求很常见，审计公司会经验审计这种业务接口 
2. 一些技术实现的安全问题，也有必要让审计公司审计
3. 审计公司的交付物里需要有测试用例，测试覆盖率，测试结果等详细内容

设计公司的测试覆盖率大概在 95% 左右  
审计的同时，其他贡献者可以同时写单元测试，保证测试覆盖率

**Comment by fushang318** [comment]
@hnuyx 你提个PR吧，把内容提交到 https://github.com/sibbay-ai/cooperation-issues 的 plan 吧，这个项目是公开的，我们需要把沟通详细的内容删除掉，包括价格，保护审计公司的隐私

**Comment by fushang318** [comment]
1

**Comment by fushang318** [comment]
1
