### ISSUE TITLE
调研智能合约测试方法

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#31]
1. truffle test 测试方法：js， solidity
2. python测试方法：populus
3. 分析每个测试方法的优点和缺点：维护性、易用性、易读性等方面

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-09-11 size:0.5 @fushang318

**Comment by hnuyx** [comment]
合约测试框架，今天最终确认一下。@fushang318

**Comment by fushang318** [comment]
我赞同你的方案，用 truffle

**Comment by fushang318** [comment]
变更 deadline: 2018-09-12

**Comment by fushang318** [comment]
1
