### ISSUE TITLE
truffle test

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#35]
添加各个接口的truffle testcase
需要先写出每个case，然后完成case内容。

因为是要学习使用测试导向的合约开发，所以以这次的开发为模板，建立一个合约开发流程。将测试和合约开发进行分离。为以后的测试导向的合约开发打基础。

note：当前的token合约是先实现了合约开发的。前期的流程问题。

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-09-30 size:1 @fushang318

**Comment by hnuyx** [comment]
变更 deadline:2018-10-07 @fushang318 代码比较多，加上review的时间

**Comment by fushang318** [comment]
变更 deadline:2018-10-07

**Comment by fushang318** [comment]
变更 deadline:2018-10-08

**Comment by hnuyx** [comment]
申请修改size为2, 原因: 代码比较多是一方面，truffle的一些坑也要解决。
