### ISSUE TITLE
关于token合约review

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/token#36]
已经修改：
1、对于所有的transfer均对from和to账号进行lockbalance的refresh；
2、增加对外的refresh函数
3、增加了test

需要修改：
1、availableBalanceOf和lockedBalanceOf函数需要重写支持按时间的更新
2、merge到develop分支
3、在实际ropsten上跑通测试后提交到master
deadline：2018-10-8 
@hnuyx @fushang318

**Comment by hnuyx** [comment]
@fushang318 这个可以关闭了
