### ISSUE TITLE
需求：增加onwer账号transfer年度总量的限制

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/token#41]
增加owner账号年度释放的限制：
1、年度释放不得超过owner年初余额的10%
2、总余额以每年1月1日00:00的为准；

@hnuyx @fushang318

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-10-14 size:1 @fushang318

**Comment by hnuyx** [comment]
代码merge，可以关闭.
@fushang318 @georgeliuyu
