### ISSUE TITLE
合约部署脚本和说明

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#43]
实现合约部署的脚本和说明
可以实现手动部署

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-10-11 size:0.5 @fushang318

**Comment by fushang318** [comment]
在你写的文档基础上，我梳理了一个更傻瓜化的说明
https://github.com/sibbay-ai/token/blob/develop/doc/%E9%83%A8%E7%BD%B2%E6%93%8D%E4%BD%9C%E8%AF%B4%E6%98%8E.md

**Comment by fushang318** [comment]
issue 可以关闭了
