### ISSUE TITLE
添加event事件与测试

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#53]
1. 添加event事件：开启/关闭购买事件，开启关闭赎回事件，赎回事件，withdraw事件，refresh事件
2. 添加所有event事件的测试用例

**Comment by fushang318** [comment]
过了一遍所有智能合约写操作接口，缺少了如下事件

1. 开启购买事件
2. 关闭购买事件
3. 开始赎回事件
4. 关闭赎回事件
5. 赎回事件
6. withdraw 的操作事件
7. refresh 的操作事件

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-10-23 size:0.8 @fushang318
包括所有事件的测试cases
