### ISSUE TITLE
修改fund账户为固定账户

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#55]
1. 修改fund账户为固定账户，在constructor中传入参数，即部署合约传入参数
2. 添加releaseTokenToFund方法，owner可以将token转入fund账户
3. 添加事件ReleaseTokenToFund以及测试
4. 修改部署合约migration文件
5. 修改部署合约脚本 deploy_contract.py

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-10-29 size:0.6 @fushang318

**Comment by fushang318** [comment]
用 addTokenToFund 这个名字？你和刘总沟通？
