### ISSUE TITLE
协商路印上币问题

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#56]
上币的要求问题
1. 上币要求
2. 上币balanceOf的返回值

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-11-05 size:0.2 @fushang318
deadline时间长一点，邮件还没回我

**Comment by hnuyx** [comment]
变更 deadline:2018-11-10 @fushang318  还有些问题需要确定

**Comment by fushang318** [comment]
变更 deadline:2018-11-10
