### ISSUE TITLE
test_py测试样例的维护

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#57]
需要决定一下test_py下的python测试用例的问题。
因为最近修改了几个接口，python下的代码是否还需要维护，保证通过，需要讨论下
@fushang318

**Comment by fushang318** [comment]
你确定

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-10-31 size:0.2 @fushang318
修改test_py的测试用例
1. 修改buy/sell接口相关的case
2. 修改fund相关的case

由于case的运行时间较长，所以deadline要长一点

**Comment by fushang318** [comment]
你要给我 合并 PR 留一些时间

**Comment by fushang318** [comment]
@hnuyx 合并时间晚于 deadline 需要修改一下
