### ISSUE TITLE
关于调整余额为总余额的通知

### ISSUE THREAD

**Issue by georgeliuyu** [sibbay-ai/token#64]
在使用imtoken时：
![image](https://user-images.githubusercontent.com/16983441/48184848-2dda7780-e36e-11e8-9974-01848bc4488b.png)

说明锁定token是常见功能。故还是修改为原来的总余额的方式。

@fushang318 @hnuyx

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-11-09 size:0.2 @fushang318

**Comment by fushang318** [comment]
1
