### ISSUE TITLE
imToken安装说明

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#66]
imToken的IOS安装说明

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-11-09 size:0.2 @fushang318

**Comment by fushang318** [comment]
@hnuyx 改下时间后，提交PR吧
你可以重新写一楼

申请开发 deadline: 2018-11-12 size:0.2

**Comment by fushang318** [comment]
变更 deadline: 2018-11-10
