### ISSUE TITLE
合约逻辑修改

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#70]
一、关于冻结账户的修改
1. 删除 owner 冻结账户权限
2. owner只可以冻结账户锁定期余额
3. 罚款功能去掉
4. 强制自动释放开关（owner权限），只能打开，不能关闭，打开之后账号的锁定期余额不再受限制

二、关于购买/赎回接口修改
1. 删除购买接口
2. 赎回接口只保留一个关闭，不能开启

**Comment by fushang318** [comment]
强制自动释放开关（owner权限），这个是针对单个账号的

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-11-17 size:1 @fushang318
