### ISSUE TITLE
SHT资产管理教程文档

### ISSUE THREAD

**Issue by hnuyx** [sibbay-ai/token#73]
android imToken 2.0 管理教程

**Comment by hnuyx** [comment]
申请开发 deadline: 2018-11-19 size:0.2 @fushang318

**Comment by fushang318** [comment]
三个文档要今天完成！！

**Comment by hnuyx** [comment]
怎么会三个文档 @fushang318

**Comment by hnuyx** [comment]
申请size变更为0.4
1. 整理Apple imToken1.0安装教程
2. 添加Apple imToken2.0安装教程
3. 添加SHT资产查询文档-Android版、Apple imToken1.0版、Apple imToken2.0版

请打开新添加文档的权限 @fushang318 
https://shimo.im/docs/n7PXhU92v4wkk5v2

**Comment by fushang318** [comment]
![image](https://user-images.githubusercontent.com/326242/48670182-18bfce80-eb4e-11e8-8193-e8c0cff6fc6d.png)
你应该有权限吧
